# fly.toml app configuration file generated for go-htmx on 2023-09-11T22:44:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "go-htmx"
primary_region = "iad"

[build]

[http_service]
internal_port = 8069
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
